// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"

class Vtop__Syms;
class Vtop___024unit;


class Vtop___024root final : public VerilatedModule {
  public:
    // CELLS
    Vtop___024unit* __PVT____024unit;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst_n,0,0);
        CData/*0:0*/ top__DOT__valid_wbu_to_ifu;
        CData/*0:0*/ top__DOT__ready_wbu_to_ifu;
        CData/*0:0*/ top__DOT__valid_ifu_to_idu;
        CData/*0:0*/ top__DOT__ready_ifu_to_idu;
        CData/*0:0*/ top__DOT__ifu_arvalid;
        CData/*0:0*/ top__DOT__ifu_arready;
        CData/*1:0*/ top__DOT__ifu_rresp;
        CData/*0:0*/ top__DOT__ifu_rvalid;
        CData/*0:0*/ top__DOT__ifu_rready;
        CData/*0:0*/ top__DOT__useless1;
        CData/*0:0*/ top__DOT__useless2;
        CData/*0:0*/ top__DOT__useless3;
        CData/*0:0*/ top__DOT__useless4;
        CData/*0:0*/ top__DOT__axi_arvalid;
        CData/*0:0*/ top__DOT__axi_arready;
        CData/*1:0*/ top__DOT__axi_rresp;
        CData/*0:0*/ top__DOT__axi_rvalid;
        CData/*0:0*/ top__DOT__axi_rready;
        CData/*0:0*/ top__DOT__axi_awvalid;
        CData/*0:0*/ top__DOT__axi_awready;
        CData/*3:0*/ top__DOT__axi_wstrb;
        CData/*0:0*/ top__DOT__axi_wvalid;
        CData/*0:0*/ top__DOT__axi_wready;
        CData/*1:0*/ top__DOT__axi_bresp;
        CData/*0:0*/ top__DOT__axi_bvalid;
        CData/*0:0*/ top__DOT__axi_bready;
        CData/*0:0*/ top__DOT__uart_arvalid;
        CData/*0:0*/ top__DOT__uart_arready;
        CData/*1:0*/ top__DOT__uart_rresp;
        CData/*0:0*/ top__DOT__uart_rvalid;
        CData/*0:0*/ top__DOT__uart_rready;
        CData/*0:0*/ top__DOT__uart_awvalid;
        CData/*0:0*/ top__DOT__uart_awready;
        CData/*3:0*/ top__DOT__uart_wstrb;
        CData/*0:0*/ top__DOT__uart_wvalid;
        CData/*0:0*/ top__DOT__uart_wready;
        CData/*1:0*/ top__DOT__uart_bresp;
        CData/*0:0*/ top__DOT__uart_bvalid;
        CData/*0:0*/ top__DOT__uart_bready;
        CData/*0:0*/ top__DOT__sram_arvalid;
        CData/*0:0*/ top__DOT__sram_arready;
        CData/*1:0*/ top__DOT__sram_rresp;
        CData/*0:0*/ top__DOT__sram_rvalid;
        CData/*0:0*/ top__DOT__sram_rready;
        CData/*0:0*/ top__DOT__sram_awvalid;
        CData/*0:0*/ top__DOT__sram_awready;
        CData/*3:0*/ top__DOT__sram_wstrb;
        CData/*0:0*/ top__DOT__sram_wvalid;
        CData/*0:0*/ top__DOT__sram_wready;
        CData/*1:0*/ top__DOT__sram_bresp;
        CData/*0:0*/ top__DOT__sram_bvalid;
        CData/*0:0*/ top__DOT__sram_bready;
        CData/*0:0*/ top__DOT__clint_arvalid;
        CData/*0:0*/ top__DOT__clint_arready;
        CData/*1:0*/ top__DOT__clint_rresp;
        CData/*0:0*/ top__DOT__clint_rvalid;
        CData/*0:0*/ top__DOT__clint_rready;
        CData/*0:0*/ top__DOT__clint_awvalid;
        CData/*0:0*/ top__DOT__clint_awready;
        CData/*3:0*/ top__DOT__clint_wstrb;
        CData/*0:0*/ top__DOT__clint_wvalid;
        CData/*0:0*/ top__DOT__clint_wready;
    };
    struct {
        CData/*1:0*/ top__DOT__clint_bresp;
        CData/*0:0*/ top__DOT__clint_bvalid;
        CData/*0:0*/ top__DOT__clint_bready;
        CData/*0:0*/ top__DOT__a_in_src_idu_to_exu;
        CData/*1:0*/ top__DOT__b_in_src_idu_to_exu;
        CData/*2:0*/ top__DOT__pc_srcs_idu_to_exu;
        CData/*0:0*/ top__DOT__adder_a_src_idu_to_exu;
        CData/*0:0*/ top__DOT__adder_out_src_idu_to_exu;
        CData/*3:0*/ top__DOT__alu_op_idu_to_exu;
        CData/*0:0*/ top__DOT__MemRead_idu_to_exu;
        CData/*0:0*/ top__DOT__MemWrite_idu_to_exu;
        CData/*7:0*/ top__DOT__wmask_idu_to_exu;
        CData/*2:0*/ top__DOT__rmask_idu_to_exu;
        CData/*0:0*/ top__DOT__wb_src_idu_to_exu;
        CData/*0:0*/ top__DOT__csr_write_idu_to_exu;
        CData/*0:0*/ top__DOT__csr_wdata_src_idu_to_exu;
        CData/*0:0*/ top__DOT__reg_write_idu_to_exu;
        CData/*0:0*/ top__DOT__valid_idu_to_exu;
        CData/*0:0*/ top__DOT__ready_idu_to_exu;
        CData/*0:0*/ top__DOT__csr_write;
        CData/*4:0*/ top__DOT__waddr;
        CData/*0:0*/ top__DOT__reg_write;
        CData/*0:0*/ top__DOT__MemRead_exu_to_lsu;
        CData/*0:0*/ top__DOT__MemWrite_exu_to_lsu;
        CData/*7:0*/ top__DOT__wmask_exu_to_lsu;
        CData/*2:0*/ top__DOT__rmask_exu_to_lsu;
        CData/*0:0*/ top__DOT__wb_src_exu_to_lsu;
        CData/*0:0*/ top__DOT__csr_write_exu_to_lsu;
        CData/*0:0*/ top__DOT__csr_wdta_src_exu_to_lsu;
        CData/*0:0*/ top__DOT__reg_write_exu_to_lsu;
        CData/*4:0*/ top__DOT__waddr_exu_to_lsu;
        CData/*0:0*/ top__DOT__valid_exu_to_lsu;
        CData/*0:0*/ top__DOT__ready_exu_to_lsu;
        CData/*0:0*/ top__DOT__wb_src_lsu_to_wbu;
        CData/*0:0*/ top__DOT__csr_write_lsu_to_wbu;
        CData/*0:0*/ top__DOT__csr_wdata_src_lsu_to_wbu;
        CData/*0:0*/ top__DOT__reg_write_lsu_to_wbu;
        CData/*4:0*/ top__DOT__waddr_lsu_to_wbu;
        CData/*0:0*/ top__DOT__valid_lsu_to_wbu;
        CData/*0:0*/ top__DOT__ready_lsu_to_wbu;
        CData/*0:0*/ top__DOT__lsu_arvalid;
        CData/*0:0*/ top__DOT__lsu_arready;
        CData/*1:0*/ top__DOT__lsu_rresp;
        CData/*0:0*/ top__DOT__lsu_rvalid;
        CData/*0:0*/ top__DOT__lsu_rready;
        CData/*0:0*/ top__DOT__lsu_awvalid;
        CData/*0:0*/ top__DOT__lsu_awready;
        CData/*3:0*/ top__DOT__lsu_wstrb;
        CData/*0:0*/ top__DOT__lsu_wvalid;
        CData/*0:0*/ top__DOT__lsu_wready;
        CData/*1:0*/ top__DOT__lsu_bresp;
        CData/*0:0*/ top__DOT__lsu_bvalid;
        CData/*0:0*/ top__DOT__lsu_bready;
        CData/*4:0*/ top__DOT__IFU__DOT__LFSR;
        CData/*4:0*/ top__DOT__IFU__DOT__arvalid_delay;
        CData/*4:0*/ top__DOT__IFU__DOT__rready_delay;
        CData/*0:0*/ top__DOT__IFU__DOT__lfsr_in;
        CData/*0:0*/ top__DOT__IFU__DOT__arvalid;
        CData/*0:0*/ top__DOT__IFU__DOT__rready;
        CData/*2:0*/ top__DOT__IFU__DOT__current_state;
        CData/*2:0*/ top__DOT__IFU__DOT__next_state;
        CData/*0:0*/ top__DOT__AXI_Arbiter__DOT__rlast_o_a;
        CData/*3:0*/ top__DOT__AXI_Arbiter__DOT__rid_o_a;
        CData/*0:0*/ top__DOT__AXI_Arbiter__DOT__awready_o_a;
    };
    struct {
        CData/*0:0*/ top__DOT__AXI_Arbiter__DOT__wready_o_a;
        CData/*1:0*/ top__DOT__AXI_Arbiter__DOT__bresp_o_a;
        CData/*3:0*/ top__DOT__AXI_Arbiter__DOT__bid_o_a;
        CData/*0:0*/ top__DOT__AXI_Arbiter__DOT__bvalid_o_a;
        CData/*0:0*/ top__DOT__AXI_Arbiter__DOT__rlast_o_b;
        CData/*3:0*/ top__DOT__AXI_Arbiter__DOT__rid_o_b;
        CData/*3:0*/ top__DOT__AXI_Arbiter__DOT__bid_o_b;
        CData/*3:0*/ top__DOT__AXI_Arbiter__DOT__arid_o;
        CData/*7:0*/ top__DOT__AXI_Arbiter__DOT__arlen_o;
        CData/*2:0*/ top__DOT__AXI_Arbiter__DOT__arsize_o;
        CData/*1:0*/ top__DOT__AXI_Arbiter__DOT__arburst_o;
        CData/*3:0*/ top__DOT__AXI_Arbiter__DOT__awid_o;
        CData/*7:0*/ top__DOT__AXI_Arbiter__DOT__awlen_o;
        CData/*2:0*/ top__DOT__AXI_Arbiter__DOT__awsize_o;
        CData/*1:0*/ top__DOT__AXI_Arbiter__DOT__awburst_o;
        CData/*0:0*/ top__DOT__AXI_Arbiter__DOT__wlast_o;
        CData/*0:0*/ top__DOT__AXI_Arbiter__DOT__ar_switch;
        CData/*0:0*/ top__DOT__AXI_Arbiter__DOT__r_switch;
        CData/*0:0*/ top__DOT__AXI_Arbiter__DOT__aw_switch;
        CData/*0:0*/ top__DOT__AXI_Arbiter__DOT__w_switch;
        CData/*0:0*/ top__DOT__AXI_Arbiter__DOT__b_switch;
        CData/*0:0*/ top__DOT__Xbar__DOT__axi_rlast_o;
        CData/*3:0*/ top__DOT__Xbar__DOT__axi_rid_o;
        CData/*3:0*/ top__DOT__Xbar__DOT__axi_bid_o;
        CData/*3:0*/ top__DOT__Xbar__DOT__sram_arid_o;
        CData/*7:0*/ top__DOT__Xbar__DOT__sram_arlen_o;
        CData/*2:0*/ top__DOT__Xbar__DOT__sram_arsize_o;
        CData/*1:0*/ top__DOT__Xbar__DOT__sram_arburst_o;
        CData/*3:0*/ top__DOT__Xbar__DOT__sram_awid_o;
        CData/*7:0*/ top__DOT__Xbar__DOT__sram_awlen_o;
        CData/*2:0*/ top__DOT__Xbar__DOT__sram_awsize_o;
        CData/*1:0*/ top__DOT__Xbar__DOT__sram_awburst_o;
        CData/*0:0*/ top__DOT__Xbar__DOT__sram_wlast_o;
        CData/*3:0*/ top__DOT__Xbar__DOT__uart_arid_o;
        CData/*7:0*/ top__DOT__Xbar__DOT__uart_arlen_o;
        CData/*2:0*/ top__DOT__Xbar__DOT__uart_arsize_o;
        CData/*1:0*/ top__DOT__Xbar__DOT__uart_arburst_o;
        CData/*3:0*/ top__DOT__Xbar__DOT__uart_awid_o;
        CData/*7:0*/ top__DOT__Xbar__DOT__uart_awlen_o;
        CData/*2:0*/ top__DOT__Xbar__DOT__uart_awsize_o;
        CData/*1:0*/ top__DOT__Xbar__DOT__uart_awburst_o;
        CData/*0:0*/ top__DOT__Xbar__DOT__uart_wlast_o;
        CData/*3:0*/ top__DOT__Xbar__DOT__clint_arid_o;
        CData/*7:0*/ top__DOT__Xbar__DOT__clint_arlen_o;
        CData/*2:0*/ top__DOT__Xbar__DOT__clint_arsize_o;
        CData/*1:0*/ top__DOT__Xbar__DOT__clint_arburst_o;
        CData/*3:0*/ top__DOT__Xbar__DOT__clint_awid_o;
        CData/*7:0*/ top__DOT__Xbar__DOT__clint_awlen_o;
        CData/*2:0*/ top__DOT__Xbar__DOT__clint_awsize_o;
        CData/*1:0*/ top__DOT__Xbar__DOT__clint_awburst_o;
        CData/*0:0*/ top__DOT__Xbar__DOT__clint_wlast_o;
        CData/*0:0*/ top__DOT__Xbar__DOT__ar_switch;
        CData/*0:0*/ top__DOT__Xbar__DOT__r_switch;
        CData/*0:0*/ top__DOT__Xbar__DOT__aw_switch;
        CData/*0:0*/ top__DOT__Xbar__DOT__w_switch;
        CData/*0:0*/ top__DOT__Xbar__DOT__b_switch;
        CData/*3:0*/ top__DOT__Mem__DOT__arid_i;
        CData/*7:0*/ top__DOT__Mem__DOT__arlen_i;
        CData/*2:0*/ top__DOT__Mem__DOT__arsize_i;
        CData/*1:0*/ top__DOT__Mem__DOT__arburst_i;
        CData/*0:0*/ top__DOT__Mem__DOT__rlast_o;
        CData/*0:0*/ top__DOT__Mem__DOT__ar_state;
        CData/*0:0*/ top__DOT__Mem__DOT__r_state;
        CData/*0:0*/ top__DOT__Mem__DOT__aw_state;
    };
    struct {
        CData/*0:0*/ top__DOT__Mem__DOT__w_state;
        CData/*0:0*/ top__DOT__Mem__DOT__b_state;
        CData/*3:0*/ top__DOT__Mem__DOT__wstrb;
        CData/*0:0*/ top__DOT__Mem__DOT__wvalid;
        CData/*0:0*/ top__DOT__Mem__DOT__flag_waddr;
        CData/*0:0*/ top__DOT__Mem__DOT__flag_wdata;
        CData/*0:0*/ top__DOT__Mem__DOT__flag_rdata;
        CData/*0:0*/ top__DOT__Mem__DOT__flag_raddr;
        CData/*0:0*/ top__DOT__Mem__DOT__flag_write;
        CData/*4:0*/ top__DOT__Mem__DOT__rdata_counter;
        CData/*4:0*/ top__DOT__Mem__DOT__wdata_counter;
        CData/*4:0*/ top__DOT__Mem__DOT__w_delay;
        CData/*4:0*/ top__DOT__Mem__DOT__r_delay;
        CData/*4:0*/ top__DOT__Mem__DOT__LFSR;
        CData/*0:0*/ top__DOT__Mem__DOT__lfsr_in;
        CData/*1:0*/ top__DOT__Mem__DOT__write_box;
        CData/*0:0*/ top__DOT__UART__DOT__rlast_o;
        CData/*0:0*/ top__DOT__UART__DOT__ar_state;
        CData/*0:0*/ top__DOT__UART__DOT__r_state;
        CData/*0:0*/ top__DOT__UART__DOT__aw_state;
        CData/*0:0*/ top__DOT__UART__DOT__w_state;
        CData/*0:0*/ top__DOT__UART__DOT__b_state;
        CData/*3:0*/ top__DOT__UART__DOT__wstrb;
        CData/*0:0*/ top__DOT__UART__DOT__wvalid;
        CData/*0:0*/ top__DOT__UART__DOT__flag_waddr;
        CData/*0:0*/ top__DOT__UART__DOT__flag_wdata;
        CData/*0:0*/ top__DOT__UART__DOT__flag_rdata;
        CData/*0:0*/ top__DOT__UART__DOT__flag_raddr;
        CData/*0:0*/ top__DOT__UART__DOT__flag_write;
        CData/*4:0*/ top__DOT__UART__DOT__rdata_counter;
        CData/*4:0*/ top__DOT__UART__DOT__wdata_counter;
        CData/*4:0*/ top__DOT__UART__DOT__w_delay;
        CData/*4:0*/ top__DOT__UART__DOT__r_delay;
        CData/*4:0*/ top__DOT__UART__DOT__LFSR;
        CData/*0:0*/ top__DOT__UART__DOT__lfsr_in;
        CData/*1:0*/ top__DOT__UART__DOT__write_box;
        CData/*0:0*/ top__DOT__CLINT__DOT__rlast_o;
        CData/*0:0*/ top__DOT__CLINT__DOT__ar_state;
        CData/*0:0*/ top__DOT__CLINT__DOT__r_state;
        CData/*0:0*/ top__DOT__CLINT__DOT__aw_state;
        CData/*0:0*/ top__DOT__CLINT__DOT__w_state;
        CData/*0:0*/ top__DOT__CLINT__DOT__b_state;
        CData/*3:0*/ top__DOT__CLINT__DOT__wstrb;
        CData/*0:0*/ top__DOT__CLINT__DOT__wvalid;
        CData/*0:0*/ top__DOT__CLINT__DOT__flag_waddr;
        CData/*0:0*/ top__DOT__CLINT__DOT__flag_wdata;
        CData/*0:0*/ top__DOT__CLINT__DOT__flag_rdata;
        CData/*0:0*/ top__DOT__CLINT__DOT__flag_raddr;
        CData/*0:0*/ top__DOT__CLINT__DOT__flag_write;
        CData/*4:0*/ top__DOT__CLINT__DOT__rdata_counter;
        CData/*4:0*/ top__DOT__CLINT__DOT__wdata_counter;
        CData/*4:0*/ top__DOT__CLINT__DOT__w_delay;
        CData/*4:0*/ top__DOT__CLINT__DOT__r_delay;
        CData/*4:0*/ top__DOT__CLINT__DOT__LFSR;
        CData/*0:0*/ top__DOT__CLINT__DOT__lfsr_in;
        CData/*1:0*/ top__DOT__CLINT__DOT__write_box;
        CData/*1:0*/ top__DOT__IDU__DOT__current_state;
        CData/*1:0*/ top__DOT__IDU__DOT__next_state;
        CData/*0:0*/ top__DOT__EXU__DOT__a_in_src;
        CData/*1:0*/ top__DOT__EXU__DOT__b_in_src;
        CData/*2:0*/ top__DOT__EXU__DOT__pc_srcs;
        CData/*0:0*/ top__DOT__EXU__DOT__adder_a_src;
        CData/*0:0*/ top__DOT__EXU__DOT__adder_out_src;
        CData/*3:0*/ top__DOT__EXU__DOT__alu_op;
    };
    struct {
        CData/*1:0*/ top__DOT__EXU__DOT__current_state;
        CData/*1:0*/ top__DOT__EXU__DOT__next_state;
        CData/*0:0*/ top__DOT__LSU__DOT__rlast_i;
        CData/*3:0*/ top__DOT__LSU__DOT__rid_i;
        CData/*2:0*/ top__DOT__LSU__DOT__rmask;
        CData/*0:0*/ top__DOT__LSU__DOT__flag;
        CData/*0:0*/ top__DOT__LSU__DOT__wvalid_tmp;
        CData/*4:0*/ top__DOT__LSU__DOT__LFSR;
        CData/*4:0*/ top__DOT__LSU__DOT__arvalid_delay;
        CData/*4:0*/ top__DOT__LSU__DOT__rready_delay;
        CData/*4:0*/ top__DOT__LSU__DOT__awvalid_delay;
        CData/*4:0*/ top__DOT__LSU__DOT__wvalid_delay;
        CData/*4:0*/ top__DOT__LSU__DOT__bready_delay;
        CData/*0:0*/ top__DOT__LSU__DOT__lfsr_in;
        CData/*0:0*/ top__DOT__LSU__DOT__arvalid;
        CData/*0:0*/ top__DOT__LSU__DOT__rready;
        CData/*0:0*/ top__DOT__LSU__DOT__awvalid;
        CData/*0:0*/ top__DOT__LSU__DOT__wvalid;
        CData/*0:0*/ top__DOT__LSU__DOT__bready;
        CData/*1:0*/ top__DOT__LSU__DOT__current_state;
        CData/*1:0*/ top__DOT__LSU__DOT__next_state;
        CData/*2:0*/ top__DOT__WBU__DOT__rmask;
        CData/*0:0*/ top__DOT__WBU__DOT__wb_src;
        CData/*0:0*/ top__DOT__WBU__DOT__csr_wdata_src;
        CData/*1:0*/ top__DOT__WBU__DOT__current_state;
        CData/*1:0*/ top__DOT__WBU__DOT__next_state;
        CData/*6:0*/ __Vtableidx1;
        CData/*5:0*/ __Vtableidx2;
        CData/*5:0*/ __Vtableidx4;
        CData/*5:0*/ __Vtableidx5;
        CData/*5:0*/ __Vtableidx6;
        CData/*0:0*/ __Vdly__top__DOT__LSU__DOT__arvalid;
        CData/*0:0*/ __Vdly__top__DOT__LSU__DOT__awvalid;
        CData/*0:0*/ __Vdly__top__DOT__LSU__DOT__wvalid;
        CData/*0:0*/ __Vdly__top__DOT__LSU__DOT__bready;
        CData/*0:0*/ __Vdly__top__DOT__csr_write;
        CData/*4:0*/ __Vdlyvdim0__top__DOT__Rgefile__DOT__rf__v0;
        CData/*0:0*/ __Vdlyvset__top__DOT__Rgefile__DOT__rf__v0;
        CData/*0:0*/ __Vtrigrprev__TOP__clk;
        CData/*0:0*/ __Vtrigrprev__TOP__rst_n;
        CData/*0:0*/ __VactContinue;
        SData/*9:0*/ __Vtableidx3;
        IData/*31:0*/ top__DOT__npc_wbu_to_ifu;
        IData/*31:0*/ top__DOT__pc_ifu_to_idu;
        IData/*31:0*/ top__DOT__ifu_araddr;
        IData/*31:0*/ top__DOT__ifu_rdata;
        IData/*31:0*/ top__DOT__axi_araddr;
        IData/*31:0*/ top__DOT__axi_rdata;
        IData/*31:0*/ top__DOT__axi_awaddr;
        IData/*31:0*/ top__DOT__axi_wdata;
        IData/*31:0*/ top__DOT__uart_araddr;
        IData/*31:0*/ top__DOT__uart_rdata;
        IData/*31:0*/ top__DOT__uart_awaddr;
        IData/*31:0*/ top__DOT__uart_wdata;
        IData/*31:0*/ top__DOT__sram_araddr;
        IData/*31:0*/ top__DOT__sram_rdata;
        IData/*31:0*/ top__DOT__sram_awaddr;
        IData/*31:0*/ top__DOT__sram_wdata;
        IData/*31:0*/ top__DOT__clint_araddr;
        IData/*31:0*/ top__DOT__clint_rdata;
        IData/*31:0*/ top__DOT__clint_awaddr;
        IData/*31:0*/ top__DOT__clint_wdata;
        IData/*31:0*/ top__DOT__imm_idu_to_exu;
        IData/*31:0*/ top__DOT__csr_wdata;
    };
    struct {
        IData/*31:0*/ top__DOT__csr_rdata_l_rs1_lsu_to_wbu;
        IData/*31:0*/ top__DOT__npc_lsu_to_wbu;
        IData/*31:0*/ top__DOT__lsu_araddr;
        IData/*31:0*/ top__DOT__lsu_rdata;
        IData/*31:0*/ top__DOT__lsu_awaddr;
        IData/*31:0*/ top__DOT__lsu_wdata;
        IData/*31:0*/ top__DOT__IFU__DOT__pc;
        IData/*31:0*/ top__DOT__IFU__DOT__npc;
        IData/*31:0*/ top__DOT__IFU__DOT__arvalid_buffer;
        IData/*31:0*/ top__DOT__IFU__DOT__rready_buffer;
        IData/*31:0*/ top__DOT__IFU__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ top__DOT__IFU__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ top__DOT__IFU__DOT__unnamedblk3__DOT__j;
        IData/*31:0*/ top__DOT__IFU__DOT__unnamedblk4__DOT__i;
        IData/*31:0*/ top__DOT__IFU__DOT__unnamedblk5__DOT__j;
        IData/*31:0*/ top__DOT__Mem__DOT__araddr;
        IData/*31:0*/ top__DOT__Mem__DOT__awaddr;
        IData/*31:0*/ top__DOT__Mem__DOT__wdata;
        IData/*31:0*/ top__DOT__UART__DOT__araddr;
        IData/*31:0*/ top__DOT__UART__DOT__awaddr;
        IData/*31:0*/ top__DOT__UART__DOT__wdata;
        IData/*31:0*/ top__DOT__CLINT__DOT__araddr;
        IData/*31:0*/ top__DOT__CLINT__DOT__awaddr;
        IData/*31:0*/ top__DOT__CLINT__DOT__wdata;
        IData/*31:0*/ top__DOT__IDU__DOT__pc;
        IData/*31:0*/ top__DOT__IDU__DOT__inst;
        IData/*31:0*/ top__DOT__IDU__DOT__CSR__DOT__csr_mepc;
        IData/*31:0*/ top__DOT__IDU__DOT__CSR__DOT__csr_mstatus;
        IData/*31:0*/ top__DOT__IDU__DOT__CSR__DOT__csr_mcause;
        IData/*31:0*/ top__DOT__IDU__DOT__CSR__DOT__csr_mtvec;
        IData/*31:0*/ top__DOT__EXU__DOT__pc;
        IData/*31:0*/ top__DOT__EXU__DOT__rs1;
        IData/*31:0*/ top__DOT__EXU__DOT__rs2;
        IData/*31:0*/ top__DOT__EXU__DOT__imm;
        IData/*31:0*/ top__DOT__EXU__DOT__csr_rdata;
        IData/*31:0*/ top__DOT__EXU__DOT__a_in;
        IData/*31:0*/ top__DOT__EXU__DOT__b_in;
        IData/*31:0*/ top__DOT__EXU__DOT__pc_new;
        IData/*31:0*/ top__DOT__EXU__DOT__alu_result;
        IData/*31:0*/ top__DOT__LSU__DOT__alu_result;
        IData/*31:0*/ top__DOT__LSU__DOT__rs1;
        IData/*31:0*/ top__DOT__LSU__DOT__rs2;
        IData/*31:0*/ top__DOT__LSU__DOT__csr_rdata_l_rs1;
        IData/*31:0*/ top__DOT__LSU__DOT__wdata;
        IData/*31:0*/ top__DOT__LSU__DOT__arvalid_buffer;
        IData/*31:0*/ top__DOT__LSU__DOT__rready_buffer;
        IData/*31:0*/ top__DOT__LSU__DOT__awvalid_buffer;
        IData/*31:0*/ top__DOT__LSU__DOT__wvalid_buffer;
        IData/*31:0*/ top__DOT__LSU__DOT__bready_buffer;
        IData/*31:0*/ top__DOT__LSU__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ top__DOT__LSU__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ top__DOT__LSU__DOT__unnamedblk3__DOT__j;
        IData/*31:0*/ top__DOT__LSU__DOT__unnamedblk4__DOT__i;
        IData/*31:0*/ top__DOT__LSU__DOT__unnamedblk5__DOT__j;
        IData/*31:0*/ top__DOT__LSU__DOT__unnamedblk6__DOT__i;
        IData/*31:0*/ top__DOT__LSU__DOT__unnamedblk7__DOT__j;
        IData/*31:0*/ top__DOT__LSU__DOT__unnamedblk8__DOT__i;
        IData/*31:0*/ top__DOT__LSU__DOT__unnamedblk9__DOT__j;
        IData/*31:0*/ top__DOT__LSU__DOT__unnamedblk10__DOT__i;
        IData/*31:0*/ top__DOT__LSU__DOT__unnamedblk11__DOT__j;
        IData/*31:0*/ top__DOT__WBU__DOT__mem_data;
        IData/*31:0*/ top__DOT__WBU__DOT__datamem_readdata;
        IData/*31:0*/ top__DOT__WBU__DOT__alu_result;
        IData/*31:0*/ top__DOT__WBU__DOT__rs1;
    };
    struct {
        IData/*31:0*/ top__DOT__WBU__DOT__csr_rdata_l_rs1;
        IData/*31:0*/ __Vdly__top__DOT__IFU__DOT__npc;
        IData/*31:0*/ __Vdly__top__DOT__IDU__DOT__pc;
        IData/*31:0*/ __Vdly__top__DOT__IDU__DOT__inst;
        IData/*31:0*/ __Vdly__top__DOT__IDU__DOT__CSR__DOT__csr_mstatus;
        IData/*31:0*/ __Vdlyvval__top__DOT__Rgefile__DOT__rf__v0;
        IData/*31:0*/ __VstlIterCount;
        IData/*31:0*/ __VactIterCount;
        QData/*63:0*/ top__DOT__CLINT__DOT__time_counter;
        VlUnpacked<IData/*31:0*/, 4> top__DOT__csr_reg;
        VlUnpacked<IData/*31:0*/, 4> top__DOT____Vcellout__IDU__csr_reg;
        VlUnpacked<IData/*31:0*/, 32> top__DOT__reg_file;
        VlUnpacked<IData/*31:0*/, 32> top__DOT____Vcellout__Rgefile__reg_file;
        VlUnpacked<IData/*31:0*/, 32> top__DOT__IFU__DOT__araddr_buffer;
        VlUnpacked<IData/*31:0*/, 4> top__DOT__IDU__DOT____Vcellout__CSR__csr_reg;
        VlUnpacked<IData/*31:0*/, 32> top__DOT__Rgefile__DOT__rf;
        VlUnpacked<IData/*31:0*/, 32> top__DOT__LSU__DOT__araddr_buffer;
        VlUnpacked<IData/*31:0*/, 32> top__DOT__LSU__DOT__awaddr_buffer;
        VlUnpacked<IData/*31:0*/, 32> top__DOT__LSU__DOT__wdata_buffer;
        VlUnpacked<CData/*3:0*/, 32> top__DOT__LSU__DOT__wstrb_buffer;
        VlUnpacked<CData/*0:0*/, 5> __Vm_traceActivity;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
